config/urls.py
from django.contrib import admin
from django.urls import path, include
import reservation.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('reservation/', include('reservation.urls')),
    path('', reservation.views.index),
]

reservation/urls.py
from django.urls import path
from . import views

app_name = "reservation"

urlpatterns = [
    path('', views.index, name="index"),
    path('reservation/', views.reservation, name="reservation"),
    path('check/<int:id>', views.check, name="check"),
    path('enter/', views.enter, name="enter"),
    path('enterChceck/', views.enterCheck, name="enterCheck"),
    path('reservation_create/', views.create, name="create"),
]

reservation/models.py
from django.db import models
from django.utils import timezone
import datetime as dt

# Create your models here.
class Reservation(models.Model):
    name = models.CharField(max_length=20)
    phoneNumber = models.CharField(max_length=13)
    schoolName = models.CharField(max_length=20)
    gradeNumber = models.IntegerField()
    regDate = models.DateTimeField(default=timezone.now())
    useTicket = models.IntegerField(default="0")
    useDate = models.DateTimeField(default=dt.datetime.strptime("1900-01-01 00:00:00", "%Y-%m-%d %H:%M:%S"))

    def __str__(self):
        return self.name

reservation/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Reservation

# Create your views here.
def index(request):
    #return HttpResponse('예약사이트')
    return render(request, 'reservation/index.html')

def reservation(request):
    return render(request, 'reservation/reservation.html')

def check(request, id):
    rlist = get_object_or_404(Reservation, pk=id)
    context = {'rlist': rlist}
    return render(request, 'reservation/list.html', context)

def enter(request):
    return render(request, 'reservation/enter.html')

def enterCheck(request):
    q = get_object_or_404(Reservation, name=request.POST.get('name'), phoneNumber=request.POST.get('phoneNumber'))
    context = {'id': q}
    return render(request, 'reservation/enterqr.html', context)

def create(request):
    r = Reservation(name=request.POST.get('name'), phoneNumber=request.POST.get('phoneNumber'), schoolName=request.POST.get('schoolName'), gradeNumber=request.POST.get('gradeNumber'))
    r.save()
    return redirect('reservation:check', id=r.id)

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg bl-light">
        <div class="container-fluid">
            <span class="navbar-brand mb-0 h1">영재중 SW박람회</span>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">처음으로</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'reservation:reservation' %}">사전 참가등록</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'reservation:enter' %}">입장하기</a>
                </li>
            </ul>
            </div>          
        </div>
    </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
</body>
</html>

templates/reservation/enter.html
{% extends 'base.html' %}
{% block content %}

<h5>입장하기</h5>
<form method="post" action="{% url 'reservation:enterCheck' %}">
    {% csrf_token %}
    <div class="form-floating mt-2">
        <input type="text" id="name" name="name" class="form-control" placeholder="이름">
        <label for="name">이름</label>
    </div>
    <div class="form-floating mt-2">
        <input type="text" id="phoneNumber" name="phoneNumber" class="form-control" placeholder="전화번호">
        <label for="phoneNumber">전화번호</label>
    </div>
    <div class="mt-2">
        <button type="submit" class="btn btn-primary">확인하기</button>
    </div>
</form>
{% endblock %}

templates/reservation/enterqr.html
{% extends 'base.html' %}
{% block content %}
{% load qr_code %}
{{ id.id }}
{% qr_from_text "id.name" size="L" %}
{% endblock %}

templates/reservation/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="text-center">
    <h3>당신의, 당신에 의한, 당신을 위한 SW박람회가 찾아옵니다.</h3>
    <img src="{% static 'index.jpg' %}" width="50%" class="m-3">
    <div>사전 참가등록 후 참여하실 수 있습니다.</div>
</div>

{% endblock %}

templates/reservation/list.html
{% extends 'base.html' %}
{% block content %}

<h5>예약내역 확인</h5>
<div>이름: {{ rlist.name }}</div>
<div>전화번호: {{ rlist.phoneNumber }}</div>
<div>학교: {{ rlist.schoolName }}</div>
<div>학년: {{ rlist.gradeNumber }}</div>
<div>등록: {{ rlist.regDate }}</div>
<div>현재상태:
     {% if rlist.useTicket == 0 %}
     입장가능
     {% else %}
     입장불가
     {% endif %}
</div>

{% endblock %}

templates/reservation/reservation.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<h5>사전 참가등록</h5>
<div>
    <small class="text-muted">
        아래 정보를 입력하여 사전 참가등록 해주세요.
    </small>
</div>
<form method="post" action="{% url 'reservation:create' %}">
    {% csrf_token %}
    <div class="form-floating mt-2">
        <input type="text" id="name" name="name" class="form-control" placeholder="이름">
        <label for="name">이름</label>
    </div>
    <div class="form-floating mt-2">
        <input type="text" id="phoneNumber" name="phoneNumber" class="form-control" placeholder="전화번호">
        <label for="phoneNumber">전화번호</label>
    </div>
    <div class="form-floating mt-2">
        <input type="text" id="schoolName" name="schoolName" class="form-control" placeholder="학교이름">
        <label for="schoolName">학교이름</label>
    </div>
    <div class="form-floating mt-2">
        <select id="gradeNumber" name="gradeNumber" class="form-select">
            <option value="1">1학년</option>
            <option value="2">2학년</option>
            <option value="3">3학년</option>
        </select>
        <label for="gradeNumber">학년</label>
    </div>
    <div class="mt-2">
        <button type="submit" class="btn btn-primary">사전등록하기</button>
    </div>
</form>

{% endblock %}